remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 


title: Arquitetura e Desenvolvimento BSS
description: Site de arquitetura e desenvolvimento BSS. Aqui você encontra informações sobre nossa estratégia 
